######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 6 10:25:06 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qfwhm.hpp
SOURCES += main.cpp qfwhm.cpp
